#!/bin/sh
#                            The MIT License
#
#        Copyright (c) 2013 Marcelo Guimaraes <ataxexe@gmail.com>
# ----------------------------------------------------------------------
# Permission  is hereby granted, free of charge, to any person obtaining
# a  copy  of  this  software  and  associated  documentation files (the
# "Software"),  to  deal  in the Software without restriction, including
# without  limitation  the  rights to use, copy, modify, merge, publish,
# distribute,  sublicense,  and/or  sell  copies of the Software, and to
# permit  persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The  above  copyright  notice  and  this  permission  notice  shall be
# included  in  all  copies  or  substantial  portions  of the Software.
#                        -----------------------
# THE  SOFTWARE  IS  PROVIDED  "AS  IS",  WITHOUT  WARRANTY OF ANY KIND,
# EXPRESS  OR  IMPLIED,  INCLUDING  BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN  NO  EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM,  DAMAGES  OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT  OR  OTHERWISE,  ARISING  FROM,  OUT OF OR IN CONNECTION WITH THE
# SOFTWARE   OR   THE   USE   OR   OTHER   DEALINGS  IN  THE  SOFTWARE.

[[ -z "$SODA_DIR" ]] && SODA_DIR=$(dirname $0)
[[ -z "$SODA_USER_DIR" ]] && SODA_USER_DIR=$HOME/.soda

if ! [[ -d "$SODA_USER_DIR" ]]; then
  SODA_USER_DIR="$SODA_DIR"
fi

. "$SODA_DIR/scripts/core.sh"

function usage {
  local task="TASK"
  if [[ -z "$1" ]]; then
    import_all_namespaces
  else
    clear_help_usage
    clear_imports
    task="$1${SODA_NAMESPACE_DELIMITER}TASK"
    import "$1"
    TASKS_USAGE="${TASKS_USAGE//$1${SODA_NAMESPACE_DELIMITER}/}"
    PARAMETERS_USAGE="${PARAMETERS_USAGE//\[$1\]/}"
  fi

  echo "Usage: $(basename $0) [*PARAMETERS] $task [*ARGS] [*PARAMETERS]"
  echo ""
  printf "$PARAMETERS_USAGE\n\n"
  printf "$TASKS_USAGE\n"
  exit 1
}

SODA_PARAMETERS=()
SODA_TASK_PARAMETERS=()

for arg in "${@}"; do
  case $arg in
    --*)
      SODA_PARAMETERS+=("$arg")
      set_parameter "$arg"
      ;;
    *)
      SODA_TASK_PARAMETERS+=("$arg")
      ;;
  esac
done

# Imports common and soda namespace by default
import soda
import common

[[ "${#SODA_TASK_PARAMETERS}" = "0" ]] && usage

task_name=${SODA_TASK_PARAMETERS[0]}

if [[ -n "$task_name" ]]; then
  parse_task "$task_name" && {
    import "$NAMESPACE"
  }
  task_exists "${task_name}" || {
    log_error "Task \"$task_name\" not found."
    exit 1
  }
  broadcast "start"
  "$TASK" "${SODA_TASK_PARAMETERS[@]:1}"
  broadcast "finish"
fi
