#!/bin/sh

[[ -z "$SODA_DIR" ]] && SODA_DIR=$(pwd)
[[ -z "$SODA_USER_DIR" ]] && SODA_USER_DIR=$HOME/.soda

. $SODA_DIR/soda.conf
. $SODA_DIR/scripts/core.sh

if [[ -f "$SODA_USER_DIR/soda.conf" ]]; then
  . $SODA_USER_DIR/soda.conf
fi

SODA_RESOURCES=$SODA_USER_DIR/resources

function usage {
  local task="TASK"
  if [[ -z "$1" ]]; then
    import_all_namespaces
  else
    clear_help_usage
    clear_imports
    task="$1${SODA_NAMESPACE_DELIMITER}TASK"
    import "$1"
    TASKS_USAGE="${TASKS_USAGE//$1${SODA_NAMESPACE_DELIMITER}/}"
  fi

  echo "Usage: $(basename $0) [*PARAMETERS] $task [*ARGS] [*PARAMETERS]"
  printf "$PARAMETERS_USAGE\n\n"
  printf "$TASKS_USAGE\n"
  exit 1
}

SODA_PARAMETERS=()
SODA_TASK_PARAMETERS=()

for arg in "${@}"; do
  case $arg in
    --*)
      SODA_PARAMETERS+=("$arg")
      set_parameter "$arg"
      ;;
    *)
      SODA_TASK_PARAMETERS+=("$arg")
      ;;
  esac
done

# Imports common and soda namespace by default
import soda
import common

[[ "$#" = "0" ]] && usage

call "${SODA_TASK_PARAMETERS[@]}"
