#!/bin/sh

[[ -z "$SODA_DIR" ]] && SODA_DIR=$(pwd)
[[ -z "$SODA_USER_DIR" ]] && SODA_USER_DIR=$HOME/.soda

. $SODA_DIR/soda.conf
. $SODA_DIR/scripts/core.sh

if [[ -f "$SODA_USER_DIR/soda.conf" ]]; then
  . $SODA_USER_DIR/soda.conf
fi

SODA_RESOURCES=$SODA_USER_DIR/resources

function usage {
  echo """Usage: $0 [OPTIONS] FUNCTION
    OPTIONS:
    -o | --options FILE            Sets the file to parse as options
    -v | --verbose                 Prints debug messages
         --no-colors               Do not use colors
"""
  printf "$PUBLIC_FUNCTIONS_USAGE"
  echo ""
  exit 0
}

for arg in "${@}"; do
  case $arg in
    -v | --verbose)
      DEBUG=true
      shift
      ;;
    --no-colors)
      NO_COLORS=true
      shift
      ;;
    -o | --options)
      debug "Loading options: $2"
      . "$2"
      shift
      shift
      ;;
  esac
done

# Conventionally import common and soda namespace
import soda
import common

[[ "$#" = "0" ]] && usage

call "$@"

finish
