#!/bin/sh
#                            The MIT License
#
#        Copyright (c) 2013 Marcelo Guimaraes <ataxexe@gmail.com>
# ----------------------------------------------------------------------
# Permission  is hereby granted, free of charge, to any person obtaining
# a  copy  of  this  software  and  associated  documentation files (the
# "Software"),  to  deal  in the Software without restriction, including
# without  limitation  the  rights to use, copy, modify, merge, publish,
# distribute,  sublicense,  and/or  sell  copies of the Software, and to
# permit  persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The  above  copyright  notice  and  this  permission  notice  shall be
# included  in  all  copies  or  substantial  portions  of the Software.
#                        -----------------------
# THE  SOFTWARE  IS  PROVIDED  "AS  IS",  WITHOUT  WARRANTY OF ANY KIND,
# EXPRESS  OR  IMPLIED,  INCLUDING  BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN  NO  EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM,  DAMAGES  OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT  OR  OTHERWISE,  ARISING  FROM,  OUT OF OR IN CONNECTION WITH THE
# SOFTWARE   OR   THE   USE   OR   OTHER   DEALINGS  IN  THE  SOFTWARE.

_soda () {
  local cur
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  local aux=(${COMP_WORDS[@]:1})
  local args=()
  # When using "=" for parameters, they came splitted
  # this will remove all parameters and their values
  # TODO find a better way to do this
  local ignore_next=""
  for arg in ${aux[@]}; do
    if [[ $ignore_next ]]; then
      ignore_next=""
      continue
    fi
    if [[ ! "$arg" == "--"* ]]; then
      if [[ "$arg" == "=" ]]; then
        ignore_next=true
      else
        args+=("$arg")
      fi
    fi
  done
  local additional_args="--no-log-files --log-level=4"
  case "$cur" in
    -*)
      COMPREPLY=( $( compgen -W '$(soda bash-completion-parameter $additional_args ${args[@]})' -- $cur ) )
    ;;
    *)
      suggestions="$(soda bash-completion-task $additional_args ${args[@]})"
      if [[ $? == 0 ]]; then
        COMPREPLY=( $( compgen -W '$suggestions' -- $cur ) )
      else
        COMPREPLY=( $( compgen -f -- $cur ) )
      fi
    ;;
  esac
  return 0
}

complete -F _soda -o nospace soda
