#!/bin/sh
# soda bash-completion

_soda () {
  local cur
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  local args=()
  for word in "${COMP_WORDS[@]:1}"; do
    if [[ ! "$word" =~ ^\-\-* ]]; then
      args+=("$word")
    fi
  done
  case "$cur" in
    --*)
      COMPREPLY=( $( compgen -W '$(soda bash-completion-parameter ${args[@]})' -- $cur ) )
    ;;
    *)
      COMPREPLY=( $( compgen -W '$(soda bash-completion-task ${args[@]})' -- $cur ) )
    ;;
  esac

  return 0
}

complete -F _soda -o nospace soda
